---

- name: install packages
  package:
    name: "{{ packages }}"
    state: present

- name: install root user with changed shell
  import_tasks: create-sudo-user.yml
  # vars:
  #   username: biga
  #   shell: bash

- name: install vim
  import_tasks: install-vim.yml

# - name: install oh-my-zsh
#   import_tasks: install-oh-my-zsh.yml

- name: add ssh config
  import_tasks: ssh-config.yml
  vars:
    ssh_home: "/home/{{username}}/.ssh"
